# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oryabchu <oryabchu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/09 20:42:52 by oryabchu          #+#    #+#              #
#    Updated: 2019/04/09 20:57:56 by oryabchu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = type

SRCS = main.cpp	identify.cpp Base.cpp A.cpp	B.cpp C.cpp
HDRS = identify.hpp Base.hpp A.hpp	B.hpp C.hpp

OBJECTS = $(SRCS:.cpp=.o)

FLAGS = -std=c++98 -Wall -Werror -Wextra

CC = clang++

all: $(NAME)

$(NAME): $(OBJECTS) $(HDRS)
	@$(CC) $(FLAGS) -o $(NAME) $(OBJECTS)  -lncurses
%.o: %.cpp
	@$(CC) $(FLAGS) -c $<
clean:
	@rm -f $(OBJECTS)

fclean: clean
	@rm -f $(NAME)	

re: fclean all

.PHONY: re all clean fclean